//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginalDataForwarding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.238")]
        public string DpscIp {
            get {
                return ((string)(this["DpscIp"]));
            }
            set {
                this["DpscIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public ushort DpscPort {
            get {
                return ((ushort)(this["DpscPort"]));
            }
            set {
                this["DpscPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2102342342")]
        public uint DpscChk {
            get {
                return ((uint)(this["DpscChk"]));
            }
            set {
                this["DpscChk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte ApMartketType {
            get {
                return ((byte)(this["ApMartketType"]));
            }
            set {
                this["ApMartketType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7001")]
        public int MulticastPort {
            get {
                return ((int)(this["MulticastPort"]));
            }
            set {
                this["MulticastPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9951")]
        public ushort RawDataChannel {
            get {
                return ((ushort)(this["RawDataChannel"]));
            }
            set {
                this["RawDataChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ApMartketType
Tse: 2
Otc: 3
Tmx: 4
Opt: 5
Emerging: 6
TmxAfterHours: 7
OptAfterHours: 8

MulticastPort
Tse: 7001
Otc: 7002
Tmx: 7003
Opt: 7004
Emerging: 7005
TmxAfterHours: 7203
OptAfterHours: 7204

RawDataChannel
Tse: 9951
Otc: 9952
Tmx: 9953
Opt: 9954
Emerging: 9955
TmxAfterHours: 9960
OptAfterHours: 9961
")]
        public string Memo {
            get {
                return ((string)(this["Memo"]));
            }
            set {
                this["Memo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HeartBeatFrequency {
            get {
                return ((int)(this["HeartBeatFrequency"]));
            }
            set {
                this["HeartBeatFrequency"] = value;
            }
        }
    }
}
