//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginalDataForwarding.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.238")]
        public string DpscIp {
            get {
                return ((string)(this["DpscIp"]));
            }
            set {
                this["DpscIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public ushort DpscPort {
            get {
                return ((ushort)(this["DpscPort"]));
            }
            set {
                this["DpscPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2102342342")]
        public uint DpscChk {
            get {
                return ((uint)(this["DpscChk"]));
            }
            set {
                this["DpscChk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7001")]
        public int TseServerPort {
            get {
                return ((int)(this["TseServerPort"]));
            }
            set {
                this["TseServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9951")]
        public uint TseRawChannel {
            get {
                return ((uint)(this["TseRawChannel"]));
            }
            set {
                this["TseRawChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9952")]
        public uint OtcRawChannel {
            get {
                return ((uint)(this["OtcRawChannel"]));
            }
            set {
                this["OtcRawChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9953")]
        public uint TmxRawChannel {
            get {
                return ((uint)(this["TmxRawChannel"]));
            }
            set {
                this["TmxRawChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9954")]
        public uint OptRawChannel {
            get {
                return ((uint)(this["OptRawChannel"]));
            }
            set {
                this["OptRawChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSE")]
        public string Market {
            get {
                return ((string)(this["Market"]));
            }
            set {
                this["Market"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(我是註解) Market 欄請填 TSE  , OTC , TMX , OPT 任一文字")]
        public string MarketComment {
            get {
                return ((string)(this["MarketComment"]));
            }
            set {
                this["MarketComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7002")]
        public int OtcServerPort {
            get {
                return ((int)(this["OtcServerPort"]));
            }
            set {
                this["OtcServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7003")]
        public int TmxServerPort {
            get {
                return ((int)(this["TmxServerPort"]));
            }
            set {
                this["TmxServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7004")]
        public int OptServerPort {
            get {
                return ((int)(this["OptServerPort"]));
            }
            set {
                this["OptServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HeartBeatFrequency {
            get {
                return ((int)(this["HeartBeatFrequency"]));
            }
            set {
                this["HeartBeatFrequency"] = value;
            }
        }
    }
}
